[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.virtualenv"]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip",
  "pip install -r backend/requirements.txt"
]

[phases.build]
cmds = [
  "echo 'Build phase completed'"
]

[start]
cmd = "cd backend && gunicorn app:app --bind 0.0.0.0:$PORT --workers 4 --timeout 120"

[variables]
PYTHON_VERSION = "3.11" 