[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && gunicorn app:app --bind 0.0.0.0:$PORT --workers 4 --timeout 120"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.envs]
PYTHON_VERSION = "3.11" 